### ISSUE TITLE
Keeping the bot running

### ISSUE THREAD

**Issue by Mizuwuki** [Sitiaro/kikspambot#1]
The bot stops after a certain amount of time even though I keep Acquire wake lock on in Termux, is there a fix to this problem?

**Comment by enigmatic21** [comment]
Can't you host the bot on ngrok in Termux? Something along those lines?

**Comment by Sitiaro** [comment]
Added https://github.com/Sitiaro/kikspambot/blob/main/keep_alive.py, currently integrating it to https://github.com/Sitiaro/kikspambot/blob/main/spambot.py
This will run your bot on localhost (127.0.0.1, port: 8080), and it won't stop randomly like it usually does.

**Comment by Mizuwuki** [comment]
Alright thanks
